spring.application.name=digital-cameras

# Dev defaults (local Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/digital_cameras
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.flyway.enabled=true
